### ISSUE TITLE
ModuleNotFoundError: No module named 'provider.poses'

### ISSUE THREAD

**Issue by aThinkingNeal** [JiehongLin/SAM-6D#12]
There is no poses folder under the provider in the folder Instance_Segmentation_Model

The error is as follows:

```bash
Traceback (most recent call last):
  File "/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 30, in <module>
    from provider.poses.utils import get_obj_poses_from_template_level, load_index_level_in_level2
ModuleNotFoundError: No module named 'provider.poses'
```

**Comment by WuTanKun** [comment]
Thank you very much for the reminder. The problem occurs because we changed the location of pose-related files. To solve this error, we have changed the corresponding import path and re-uploaded the files of the template poses that were missing when updating the code. If you encounter any new problems, please feel free to raise an issue.
